@extends('layouts.app')
@section('title', __('app.search_results'))
@section('content')
@php($totalResults = $users->count() + $roles->count() + $clients->count())
<div class="page-heading"><div><h1 class="page-title">{{ __('app.search_results') }}</h1><p class="page-description">{{ $q ? __('app.search_results_for', ['query'=>$q]) : __('app.search_prompt') }}</p></div>@if($q)<span class="badge badge-primary">{{ __('app.result_count', ['count'=>$totalResults]) }}</span>@endif</div>
<form method="GET" action="{{ route('search') }}" class="search-page-form"><div class="search-field"><x-icon name="search" /><input class="form-input" type="search" name="q" value="{{ $q }}" required minlength="2" maxlength="100" placeholder="{{ __('app.search_placeholder') }}" aria-label="{{ __('app.search') }}" autofocus></div><button type="submit" class="btn btn-primary">{{ __('app.search') }}</button></form>
@if($totalResults === 0)<section class="card"><div class="empty-state"><div class="empty-icon"><x-icon name="search" /></div><h2>{{ $q ? __('app.no_results') : __('app.find_anything') }}</h2><p>{{ $q ? __('app.no_results_description') : __('app.search_prompt') }}</p></div></section>@else
<div class="stack">
    @if($users->isNotEmpty())<section class="card"><div class="card-header"><h2 class="card-title">{{ __('app.users') }}</h2><span class="badge badge-neutral">{{ $users->count() }}</span></div><div class="search-results-list">@foreach($users as $user)
@php($canManageUser = $user->id === auth()->id() || auth()->user()->is_super_admin || (!$user->is_super_admin && !$user->role?->is_owner && collect($user->role?->permissions ?? [])->every(fn($permission) => auth()->user()->canDo($permission))))
<div class="search-result"><div class="identity"><span class="avatar">{{ $user->initials() }}</span><div class="identity-info"><strong>{{ $user->name }}</strong><span dir="ltr">{{ $user->email }}</span></div></div><div class="row-actions"><span class="badge badge-neutral">{{ $user->role?->name ?? __('app.no_role') }}</span>@if($canManageUser && auth()->user()->canDo('users.update'))<a href="{{ route('users.edit', $user) }}" class="icon-button" aria-label="{{ __('app.edit_user', ['name'=>$user->name]) }}"><x-icon name="arrow-up-right" /></a>@endif</div></div>@endforeach</div></section>@endif
    @if($roles->isNotEmpty())<section class="card"><div class="card-header"><h2 class="card-title">{{ __('app.roles_permissions') }}</h2><span class="badge badge-neutral">{{ $roles->count() }}</span></div><div class="search-results-list">@foreach($roles as $role)<div class="search-result"><div class="identity"><span class="avatar role-avatar"><x-icon name="shield" /></span><div class="identity-info"><strong>{{ $role->name }}</strong><span>{{ $role->description ?: __('app.no_description') }}</span></div></div><div class="row-actions"><button type="button" class="btn btn-ghost btn-sm" data-role-users="{{ route('roles.users', $role) }}" data-role-name="{{ $role->name }}">{{ __('app.view_members') }}</button>@if(!$role->is_owner && collect($role->permissions ?? [])->every(fn($permission) => auth()->user()->canDo($permission)) && auth()->user()->canDo('roles.update'))<a class="icon-button" href="{{ route('roles.edit', $role) }}" aria-label="{{ __('app.edit_role_name', ['name'=>$role->name]) }}"><x-icon name="arrow-up-right" /></a>@endif</div></div>@endforeach</div></section>@endif
    @if($clients->isNotEmpty())<section class="card"><div class="card-header"><h2 class="card-title">{{ __('app.clients') }}</h2><span class="badge badge-neutral">{{ $clients->count() }}</span></div><div class="search-results-list">@foreach($clients as $client)<a class="search-result" href="{{ route('admin.clients.show', $client) }}"><div class="identity"><span class="avatar avatar-company">{{ mb_substr($client->name, 0, 1) }}</span><div class="identity-info"><strong>{{ $client->name }}</strong><span dir="ltr">{{ $client->email }}</span></div></div><div class="row-actions"><span class="badge {{ $client->status === 'active' ? 'badge-success' : 'badge-warning' }}">{{ __('app.'.$client->status) }}</span><x-icon name="arrow-up-right" /></div></a>@endforeach</div></section>@endif
</div>
@endif
@endsection
