@extends('layouts.app')
@section('title', __('app.clients'))
@section('content')
<div class="page-heading"><div><h1 class="page-title">{{ __('app.clients') }}</h1><p class="page-description">{{ __('app.clients_description') }}</p></div>@if(auth()->user()->canDo('clients.create'))<a class="btn btn-primary" href="{{ route('admin.clients.create') }}"><x-icon name="plus" />{{ __('app.add_client') }}</a>@endif</div>
<section class="card"><div class="card-header"><div class="inline-heading"><h2 class="card-title">{{ __('app.all_clients') }}</h2><span class="badge badge-primary">{{ $clients->total() }}</span></div><span class="muted">{{ __('app.independent_workspaces') }}</span></div>
    <form method="GET" action="{{ route('admin.clients.index') }}" class="table-toolbar filters">
        <div class="search-field"><x-icon name="search" /><input class="form-input" type="search" name="q" value="{{ request('q') }}" placeholder="{{ __('app.search_clients') }}" aria-label="{{ __('app.search_clients') }}"></div>
        <select class="form-select" name="plan" aria-label="{{ __('app.plan') }}"><option value="">{{ __('app.all_plans') }}</option>@foreach(['starter','growth','enterprise'] as $plan)<option value="{{ $plan }}" @selected(request('plan') === $plan)>{{ __('app.plan_'.$plan) }}</option>@endforeach</select>
        <select class="form-select" name="status" aria-label="{{ __('app.status') }}"><option value="">{{ __('app.all_statuses') }}</option><option value="active" @selected(request('status') === 'active')>{{ __('app.active') }}</option><option value="suspended" @selected(request('status') === 'suspended')>{{ __('app.suspended') }}</option></select>
        <button class="btn btn-secondary" type="submit"><x-icon name="filter" />{{ __('app.filter') }}</button>@if(request()->filled('q') || request()->filled('plan') || request()->filled('status'))<a class="btn btn-ghost" href="{{ route('admin.clients.index') }}">{{ __('app.clear_filters') }}</a>@endif
    </form>
    <div class="table-wrap"><table class="data-table"><thead><tr><th>{{ __('app.client') }}</th><th>{{ __('app.plan') }}</th><th>{{ __('app.team_size') }}</th><th>{{ __('app.status') }}</th><th>{{ __('app.created_at') }}</th><th>{{ __('app.actions') }}</th></tr></thead><tbody>
    @forelse($clients as $client)<tr><td><div class="identity"><span class="avatar avatar-company">{{ mb_substr($client->name, 0, 1) }}</span><div class="identity-info"><a class="table-link" href="{{ route('admin.clients.show', $client) }}">{{ $client->name }}</a><span dir="ltr">{{ $client->email }}</span></div></div></td><td><span class="badge badge-neutral">{{ __('app.plan_'.$client->plan) }}</span></td><td><span class="inline-icon"><x-icon name="users" />{{ $client->users_count }}</span></td><td><span class="badge {{ $client->status === 'active' ? 'badge-success' : 'badge-warning' }}"><span class="status-dot"></span>{{ __('app.'.$client->status) }}</span></td><td class="muted">{{ $client->created_at->translatedFormat('d M Y') }}</td><td><div class="row-actions"><a class="icon-button" href="{{ route('admin.clients.show', $client) }}" aria-label="{{ __('app.view_client', ['name'=>$client->name]) }}"><x-icon name="eye" /></a>@if(auth()->user()->canDo('clients.update'))<a class="icon-button" href="{{ route('admin.clients.edit', $client) }}" aria-label="{{ __('app.edit_client_name', ['name'=>$client->name]) }}"><x-icon name="pencil" /></a>@endif @if(auth()->user()->canDo('clients.delete'))<form method="POST" action="{{ route('admin.clients.destroy', $client) }}" data-confirm="{{ __('app.delete_client_confirm', ['name'=>$client->name]) }}">@csrf @method('DELETE')<button class="icon-button text-danger" type="submit" aria-label="{{ __('app.delete_client_name', ['name'=>$client->name]) }}"><x-icon name="trash-2" /></button></form>@endif</div></td></tr>
    @empty<tr><td colspan="6"><div class="empty-state compact"><div class="empty-icon"><x-icon name="building-2" /></div><h3>{{ __('app.no_clients') }}</h3><p>{{ request()->hasAny(['q','status','plan']) ? __('app.no_results_description') : __('app.no_clients_description') }}</p></div></td></tr>@endforelse
    </tbody></table></div>@include('partials.pagination', ['paginator'=>$clients])
</section>
@endsection
