@extends('layouts.app')
@section('title', $client->name)
@section('content')
<div class="page-heading"><div><a href="{{ route('admin.clients.index') }}" class="back-link"><x-icon name="arrow-left" />{{ __('app.back_to_clients') }}</a><div class="inline-heading"><h1 class="page-title">{{ $client->name }}</h1><span class="badge {{ $client->status === 'active' ? 'badge-success' : 'badge-warning' }}">{{ __('app.'.$client->status) }}</span></div><p class="page-description">{{ __('app.client_workspace_overview') }}</p></div>@if(auth()->user()->canDo('clients.update'))<a href="{{ route('admin.clients.edit', $client) }}" class="btn btn-primary"><x-icon name="pencil" />{{ __('app.edit_client') }}</a>@endif</div>
<div class="stats-grid stats-three">@foreach([['users','total_users','users'],['active_users','active_users','user-check'],['roles','roles_permissions','shield']] as [$key,$label,$icon])<article class="stat-card"><div class="stat-top"><span class="stat-label">{{ __('app.'.$label) }}</span><span class="stat-icon"><x-icon :name="$icon" /></span></div><strong class="stat-value">{{ $stats[$key] }}</strong></article>@endforeach</div>
<div class="split-grid">
    <section class="card"><div class="card-header"><h2 class="card-title">{{ __('app.workspace_team') }}</h2><span class="badge badge-primary">{{ $stats['users'] }}</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>{{ __('app.user') }}</th><th>{{ __('app.role') }}</th><th>{{ __('app.status') }}</th></tr></thead><tbody>@forelse($client->users as $user)<tr><td><div class="identity"><span class="avatar">{{ $user->initials() }}</span><div class="identity-info"><strong>{{ $user->name }}</strong><span dir="ltr">{{ $user->email }}</span></div></div></td><td><span class="badge badge-neutral">{{ $user->role?->name ?? __('app.no_role') }}</span></td><td><span class="badge {{ $user->status === 'active' ? 'badge-success' : 'badge-neutral' }}">{{ __('app.'.$user->status) }}</span></td></tr>@empty<tr><td colspan="3"><div class="empty-state compact"><h3>{{ __('app.no_users') }}</h3></div></td></tr>@endforelse</tbody></table></div></section>
    <aside class="card"><div class="card-header"><h2 class="card-title">{{ __('app.client_details') }}</h2><x-icon name="building-2" /></div><div class="card-body"><dl class="detail-list"><div><dt>{{ __('app.company_email') }}</dt><dd dir="ltr">{{ $client->email }}</dd></div><div><dt>{{ __('app.phone') }}</dt><dd dir="ltr">{{ $client->phone ?: __('app.not_provided') }}</dd></div><div><dt>{{ __('app.website') }}</dt><dd>@if($client->website)<a href="{{ $client->website }}" target="_blank" rel="noopener noreferrer" dir="ltr">{{ $client->website }}</a>@else{{ __('app.not_provided') }}@endif</dd></div><div><dt>{{ __('app.workspace_slug') }}</dt><dd dir="ltr">{{ $client->slug }}</dd></div><div><dt>{{ __('app.plan') }}</dt><dd><span class="badge badge-primary">{{ __('app.plan_'.$client->plan) }}</span></dd></div><div><dt>{{ __('app.created_at') }}</dt><dd>{{ $client->created_at->translatedFormat('d M Y') }}</dd></div><div><dt>{{ __('app.trial_ends_at') }}</dt><dd>{{ $client->trial_ends_at?->translatedFormat('d M Y') ?? __('app.not_set') }}</dd></div></dl>@if($client->description)<div class="detail-description"><h3 class="form-label">{{ __('app.description') }}</h3><p class="muted preserve-lines">{{ $client->description }}</p></div>@endif</div></aside>
</div>
@endsection
