@extends('layouts.app')
@section('title', __('app.send_notification'))
@section('content')
<div class="page-heading"><div><a href="{{ route('notifications.index') }}" class="back-link"><x-icon name="arrow-left" />{{ __('app.back_to_notifications') }}</a><h1 class="page-title">{{ __('app.send_notification') }}</h1><p class="page-description">{{ __('app.broadcast_description') }}</p></div></div>
<form action="{{ route('admin.notifications.store') }}" method="POST" class="split-grid form-layout">@csrf
    <div class="form-main"><section class="card"><div class="card-header"><div><h2 class="card-title">{{ __('app.message_details') }}</h2><p class="card-subtitle">{{ __('app.notification_delivery_hint') }}</p></div><x-icon name="send" /></div><div class="card-body stack"><div class="form-group"><label class="form-label" for="title">{{ __('app.notification_title') }} <span class="required">*</span></label><input class="form-input" id="title" name="title" value="{{ old('title') }}" required maxlength="120" placeholder="{{ __('app.notification_title_placeholder') }}"></div><div class="form-group"><label class="form-label" for="body">{{ __('app.message') }} <span class="required">*</span></label><textarea class="form-textarea" id="body" name="body" rows="7" required maxlength="2000" placeholder="{{ __('app.notification_body_placeholder') }}">{{ old('body') }}</textarea></div><div class="form-group"><label class="form-label" for="url">{{ __('app.destination_url') }}</label><input class="form-input" id="url" name="url" value="{{ old('url') }}" dir="ltr" maxlength="255" placeholder="/dashboard"><p class="form-help">{{ __('app.internal_url_hint') }}</p></div></div></section><div class="form-footer"><a href="{{ route('notifications.index') }}" class="btn btn-secondary">{{ __('app.cancel') }}</a><button class="btn btn-primary" type="submit"><x-icon name="send" />{{ __('app.send_notification') }}</button></div></div>
    <aside class="form-aside"><section class="card"><div class="card-header"><h2 class="card-title">{{ __('app.audience') }}</h2><x-icon name="users" /></div><div class="card-body stack"><div class="form-group"><label class="form-label" for="audience">{{ __('app.send_to') }}</label><select class="form-select" id="audience" name="audience" data-audience-select><option value="all" @selected(old('audience') === 'all')>{{ __('app.audience_all') }}</option><option value="platform" @selected(old('audience') === 'platform')>{{ __('app.audience_platform') }}</option><option value="client" @selected(old('audience') === 'client')>{{ __('app.audience_client') }}</option></select></div><div class="form-group" data-audience-client><label class="form-label" for="tenant_id">{{ __('app.client') }}</label><select class="form-select" id="tenant_id" name="tenant_id"><option value="">{{ __('app.select_client') }}</option>@foreach($clients as $client)<option value="{{ $client->id }}" @selected((string)old('tenant_id') === (string)$client->id)>{{ $client->name }}</option>@endforeach</select><p class="form-help">{{ __('app.client_audience_hint') }}</p></div><div class="notice"><x-icon name="info" /><p>{{ __('app.broadcast_hint') }}</p></div></div></section></aside>
</form>
@endsection
