@extends('layouts.app')
@section('title', __('app.notifications'))
@section('content')
<div class="page-heading"><div><h1 class="page-title">{{ __('app.notifications') }}</h1><p class="page-description">{{ __('app.notifications_description') }}</p></div><div class="page-actions">@if(auth()->user()->unreadNotifications()->exists())<form action="{{ route('notifications.read-all') }}" method="POST">@csrf<button class="btn btn-secondary" type="submit"><x-icon name="check-check" />{{ __('app.mark_all_read') }}</button></form>@endif @if(auth()->user()->canDo('notifications.send'))<a href="{{ route('admin.notifications.create') }}" class="btn btn-primary"><x-icon name="send" />{{ __('app.send_notification') }}</a>@endif</div></div>
<nav class="tabs" aria-label="{{ __('app.notifications') }}"><a href="{{ route('notifications.index') }}" class="tab {{ request('filter') !== 'unread' ? 'is-active' : '' }}">{{ __('app.notifications') }}</a><a href="{{ route('notifications.index', ['filter'=>'unread']) }}" class="tab {{ request('filter') === 'unread' ? 'is-active' : '' }}">{{ __('app.unread_notifications') }}</a></nav>
<section class="card"><div class="card-header"><div class="inline-heading"><h2 class="card-title">{{ __('app.your_notifications') }}</h2><span class="badge badge-primary">{{ $notifications->total() }}</span></div><span class="muted">{{ __('app.latest_first') }}</span></div>
<div class="notification-list">
@forelse($notifications as $notification)
    @php($data = $notification->data)
    <article class="notification-item {{ $notification->read_at ? '' : 'is-unread' }}"><div class="notification-item-icon"><x-icon name="bell" /></div><div class="notification-item-content"><div class="notification-item-title"><h3>{{ isset($data['title_key']) ? __($data['title_key']) : ($data['title'] ?? __('app.notification')) }}</h3>@unless($notification->read_at)<span class="badge badge-primary">{{ __('app.new') }}</span>@endunless</div><p class="preserve-lines">{{ isset($data['body_key']) ? __($data['body_key']) : ($data['body'] ?? '') }}</p><div class="notification-meta"><time datetime="{{ $notification->created_at->toIso8601String() }}">{{ $notification->created_at->diffForHumans() }}</time>@if(!empty($data['url']))<a href="{{ $data['url'] }}">{{ __('app.view_details') }}<x-icon name="arrow-right" /></a>@endif</div></div><div class="row-actions">@unless($notification->read_at)<form action="{{ route('notifications.read', $notification->id) }}" method="POST">@csrf @method('PATCH')<button class="icon-button" type="submit" aria-label="{{ __('app.mark_read') }}"><x-icon name="check" /></button></form>@endunless<form action="{{ route('notifications.destroy', $notification->id) }}" method="POST" data-confirm="{{ __('app.delete_notification_confirm') }}">@csrf @method('DELETE')<button class="icon-button text-danger" type="submit" aria-label="{{ __('app.delete_notification') }}"><x-icon name="trash-2" /></button></form></div></article>
@empty<div class="empty-state"><div class="empty-icon"><x-icon name="bell" /></div><h2>{{ __('app.all_caught_up') }}</h2><p>{{ __('app.no_notifications_description') }}</p></div>@endforelse
</div>@include('partials.pagination', ['paginator'=>$notifications])</section>
@endsection
