<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}" dir="{{ app()->getLocale() === 'ar' ? 'rtl' : 'ltr' }}" data-theme="{{ session('theme', 'light') === 'dark' ? 'dark' : 'light' }}">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><meta name="color-scheme" content="light dark"><title>@yield('title', __('app.welcome_back')) · Orbit</title><link rel="icon" type="image/svg+xml" href="{{ asset('assets/favicon.svg') }}"><link rel="stylesheet" href="{{ asset('assets/fonts.css') }}?v={{ filemtime(public_path('assets/fonts.css')) }}"><link rel="stylesheet" href="{{ asset('assets/app.css') }}?v={{ filemtime(public_path('assets/app.css')) }}"><script src="{{ asset('assets/theme-init.js') }}?v={{ filemtime(public_path('assets/theme-init.js')) }}"></script></head>
<body class="guest-body">
    <main class="auth-layout">
        <section class="auth-showcase" aria-label="Orbit"><a href="{{ route('login') }}" class="auth-brand"><x-brand /></a><div class="auth-showcase-content"><h1>{{ __('app.auth_tagline') }}</h1><p>{{ __('app.auth_quote') }}</p><div class="auth-orbit-art" aria-hidden="true"><span class="orbit-ring orbit-ring-1"></span><span class="orbit-ring orbit-ring-2"></span><span class="orbit-ring orbit-ring-3"></span><span class="orbit-core"><x-icon name="orbit" /></span><span class="orbit-satellite orbit-satellite-1"><x-icon name="shield" /></span><span class="orbit-satellite orbit-satellite-2"><x-icon name="users" /></span><span class="orbit-satellite orbit-satellite-3"><x-icon name="layers" /></span><span class="orbit-satellite-dot"></span></div><div class="auth-features"><span><x-icon name="shield" />{{ __('app.auth_feature_secure') }}</span><span><x-icon name="building" />{{ __('app.auth_feature_tenants') }}</span><span><x-icon name="sparkles" />{{ __('app.auth_feature_ready') }}</span></div></div><div class="auth-showcase-footer"><span>© {{ date('Y') }} Orbit</span><span>{{ __('app.auth_quote_caption') }}</span></div></section>
        <section class="auth-form-section"><div class="auth-toolbar"><a class="auth-mobile-brand" href="{{ route('login') }}"><x-brand /></a><div class="auth-toolbar-actions"><form class="locale-form" method="GET" action="{{ request()->isMethod('GET') ? url()->current() : route('login') }}"><x-icon name="globe" /><label class="sr-only" for="guest-locale">{{ __('app.language') }}</label>@if(request()->routeIs('password.reset') && is_string(request()->query('email')))<input type="hidden" name="email" value="{{ request()->query('email') }}">@endif<select name="locale" id="guest-locale" data-locale-select>@foreach(['ar'=>'العربية','en'=>'English','fr'=>'Français','de'=>'Deutsch','es'=>'Español'] as $code => $label)<option value="{{ $code }}" @selected(app()->getLocale() === $code)>{{ $label }}</option>@endforeach</select><noscript><button type="submit" class="btn btn-sm">{{ __('app.save') }}</button></noscript></form><button class="icon-button theme-toggle" type="button" data-theme-toggle aria-label="{{ __('app.appearance') }}"><span class="theme-sun"><x-icon name="sun" /></span><span class="theme-moon"><x-icon name="moon" /></span></button></div></div><div class="auth-form-container"><x-alerts />@yield('content')</div><div class="auth-form-footer"><x-icon name="lock" />{{ __('app.secure_workspace') }}</div></section>
    </main>
    <div class="toast-region" id="toast-region" aria-live="polite" aria-atomic="false"></div>@php
    $browserConfig = ['locale' => app()->getLocale(), 'strings' => ['success' => __('app.success'), 'error' => __('app.request_failed'), 'close' => __('app.close'), 'darkMode' => __('app.dark_mode'), 'lightMode' => __('app.light_mode')]];
@endphp
<script type="application/json" id="app-config">@json($browserConfig)</script><script src="{{ asset('assets/app.js') }}?v={{ filemtime(public_path('assets/app.js')) }}" defer></script>@stack('scripts')
</body>
</html>
