@extends('layouts.app')
@section('title', __('app.roles_permissions'))
@section('content')
<div class="page-heading"><div><h1 class="page-title">{{ __('app.user_management') }}</h1><p class="page-description">{{ __('app.roles_description') }}</p></div>@if(auth()->user()->canDo('roles.create'))<a class="btn btn-primary" href="{{ route('roles.create') }}"><x-icon name="plus" />{{ __('app.add_role') }}</a>@endif</div>
@include('partials.management-tabs')
<section class="card"><div class="card-header"><div class="inline-heading"><h2 class="card-title">{{ __('app.roles_permissions') }}</h2><span class="badge badge-primary">{{ $roles->total() }}</span></div><span class="muted">{{ __('app.access_control') }}</span></div>
<div class="table-wrap"><table class="data-table"><thead><tr><th>{{ __('app.role') }}</th><th>{{ __('app.permissions') }}</th><th>{{ __('app.members') }}</th><th>{{ __('app.created_at') }}</th><th>{{ __('app.actions') }}</th></tr></thead><tbody>
@forelse($roles as $role)
@php($canManageRole = !$role->is_owner && collect($role->permissions ?? [])->every(fn($permission) => auth()->user()->canDo($permission)))
<tr><td><div class="identity"><span class="avatar role-avatar"><x-icon name="shield" /></span><div class="identity-info"><strong>{{ $role->name }} @if($role->is_owner)<span class="badge badge-primary">{{ __('app.protected') }}</span>@endif</strong><span>{{ $role->description ?: __('app.no_description') }}</span></div></div></td><td><span class="badge badge-neutral">{{ __('app.permission_count', ['count' => count($role->permissions ?? [])]) }}</span></td><td><button type="button" class="btn btn-ghost btn-sm" data-role-users="{{ route('roles.users', $role) }}" data-role-name="{{ $role->name }}"><x-icon name="users" />{{ __('app.member_count', ['count'=>$role->users_count]) }}</button></td><td class="muted">{{ $role->created_at->translatedFormat('d M Y') }}</td><td><div class="row-actions">@if($canManageRole && auth()->user()->canDo('roles.update'))<a href="{{ route('roles.edit', $role) }}" class="icon-button" aria-label="{{ __('app.edit_role_name', ['name'=>$role->name]) }}"><x-icon name="pencil" /></a>@endif @if($canManageRole && auth()->user()->canDo('roles.delete'))<form action="{{ route('roles.destroy', $role) }}" method="POST" data-confirm="{{ __('app.delete_role_confirm', ['name'=>$role->name]) }}">@csrf @method('DELETE')<button type="submit" class="icon-button text-danger" aria-label="{{ __('app.delete_role_name', ['name'=>$role->name]) }}"><x-icon name="trash-2" /></button></form>@endif @if($role->is_owner)<span class="muted" title="{{ __('app.protected_role_hint') }}"><x-icon name="lock" /></span>@endif</div></td></tr>
@empty<tr><td colspan="5"><div class="empty-state compact"><div class="empty-icon"><x-icon name="shield" /></div><h3>{{ __('app.no_roles') }}</h3><p>{{ __('app.no_roles_description') }}</p></div></td></tr>@endforelse
</tbody></table></div>@include('partials.pagination', ['paginator'=>$roles])</section>
<div class="notice"><x-icon name="info" /><p>{{ __('app.role_members_hint') }}</p></div>
@endsection
